jobs:
  deploy:
    runs-on: debian 12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no username@your-server-ip << EOF
        cd /path/to/your-app
        git pull
        docker-compose down
        docker-compose up -d
        EOF
